"""
setupkit.manifest - Manifest fetcher and parser for setupkit.

Fetches a manifest.fletch file from a remote URL, parses it, and
filters its file list to only the entries relevant to a specific plugin.

A manifest.fletch file is a YAML file generated by fletcher containing
repo metadata, an optional version field, and a list of file paths with
their raw GitHub URLs.

Public API:
    ManifestData   — dataclass representing a parsed manifest.fletch
    fetch_manifest — fetch and parse a manifest.fletch from a URL
    filter_files   — filter manifest file list by path prefix and pyproject path
"""

from dataclasses import dataclass, field
from typing import Optional

import requests
import yaml

from setupkit.exceptions import ManifestError


# ---------------------------------------------------------------------------
# Data model
# ---------------------------------------------------------------------------

@dataclass
class ManifestFile:
    """
    A single file entry from a manifest.fletch file.

    Attributes:
        path: File path relative to the repo root.
        url:  Raw URL for fetching the file content.
    """

    path: str
    url: str


@dataclass
class ManifestData:
    """
    Parsed contents of a manifest.fletch file.

    Attributes:
        repo:      GitHub repo URL.
        branch:    Branch name the manifest was generated from.
        url_type:  URL type, either 'raw' or 'web'.
        generated: Timestamp string from when the manifest was generated.
        version:   Package version string, or None if not present.
        files:     List of all file entries in the manifest.
    """

    repo: str
    branch: str
    url_type: str
    generated: str
    version: Optional[str]
    files: list[ManifestFile] = field(default_factory=list)


# ---------------------------------------------------------------------------
# Fetcher
# ---------------------------------------------------------------------------

def fetch_manifest(url: str, timeout: int = 10) -> ManifestData:
    """
    Fetch and parse a manifest.fletch file from a remote URL.

    Args:
        url:     Raw URL to the manifest.fletch file.
        timeout: HTTP request timeout in seconds. Defaults to 10.

    Returns:
        A parsed ManifestData instance.

    Raises:
        ManifestError: If the URL cannot be fetched, the response is not
                       valid YAML, or required fields are missing.
    """
    try:
        response = requests.get(url, timeout=timeout)
        response.raise_for_status()
    except requests.exceptions.Timeout:
        raise ManifestError(f"Timed out fetching manifest from {url}")
    except requests.exceptions.ConnectionError as exc:
        raise ManifestError(f"Could not connect to fetch manifest from {url}: {exc}") from exc
    except requests.exceptions.HTTPError as exc:
        raise ManifestError(
            f"HTTP {response.status_code} fetching manifest from {url}"
        ) from exc
    except requests.exceptions.RequestException as exc:
        raise ManifestError(f"Failed to fetch manifest from {url}: {exc}") from exc

    try:
        data = yaml.safe_load(response.text)
    except yaml.YAMLError as exc:
        raise ManifestError(f"Could not parse manifest YAML from {url}: {exc}") from exc

    if not isinstance(data, dict):
        raise ManifestError(f"Manifest from {url} is empty or not a mapping")

    _validate_manifest(data, url)

    files = [
        ManifestFile(path=f["path"], url=f["url"])
        for f in data.get("files", [])
        if "path" in f and "url" in f
    ]

    return ManifestData(
        repo=data["repo"],
        branch=data["branch"],
        url_type=data["url_type"],
        generated=data["generated"],
        version=data.get("version"),
        files=files,
    )


# ---------------------------------------------------------------------------
# Filter
# ---------------------------------------------------------------------------

def filter_files(
    manifest: ManifestData,
    path_prefix: str,
    pyproject: str,
) -> list[ManifestFile]:
    """
    Filter a manifest's file list to only entries relevant to a specific plugin.

    Includes files whose path starts with path_prefix, plus the explicit
    pyproject.toml path.

    Args:
        manifest:    A parsed ManifestData instance.
        path_prefix: Path prefix for the plugin's source files
                     (e.g. 'python/dbkit/dbkit/').
        pyproject:   Explicit path to the plugin's pyproject.toml
                     (e.g. 'python/dbkit/pyproject.toml').

    Returns:
        Filtered list of ManifestFile entries.
    """
    return [
        f for f in manifest.files
        if f.path.startswith(path_prefix) or f.path == pyproject
    ]


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------

_REQUIRED_MANIFEST = {"repo", "branch", "url_type", "generated"}


def _validate_manifest(data: dict, url: str) -> None:
    """
    Check that all required manifest fields are present.

    Args:
        data: Parsed manifest dict.
        url:  Source URL, used in error messages.

    Raises:
        ManifestError: If any required fields are missing.
    """
    missing = _REQUIRED_MANIFEST - data.keys()
    if missing:
        raise ManifestError(
            f"Manifest from {url} missing required fields: {sorted(missing)}"
        )
