"""
ptykit/initialize.py

Config generator for ptykit.

Generates a program config yaml in
~/.config/dev-utils/ptykit/<program>.yaml.

Can be called non-interactively by supplying all parameters — useful
for container setup scripts. Falls back to interactive prompts for
any parameter not supplied.

Workflow:
    1. Accept program name + optional intercept list + optional plugins list
    2. Prompt for any missing values
    3. If config already exists, show diff and confirm overwrite
    4. Write ~/.config/dev-utils/ptykit/<program>.yaml

Public API:
    init_config — generate a ptykit config for a named program

CLI:
    ptykit init <program>
"""

import sys
from pathlib import Path

import yaml

from ptykit.config import config_path
from ptykit.exceptions import PtyKitConfigError


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def init_config(
    program: str,
    intercept: list[str] | None = None,
    plugins: list[str] | None = None,
) -> Path:
    """
    Generate a ptykit config for a named program.

    If intercept or plugins are not supplied, prompts interactively.
    If all are supplied, writes the config without any prompts — safe
    to call from container setup scripts or other automation.

    Args:
        program:   The CLI program to wrap (e.g. 'advent').
        intercept: List of commands to intercept (e.g. ['map', 'hint']).
                   If None, prompts interactively.
        plugins:   List of plugin dotted paths
                   (e.g. ['ptykit_ccc.map_plugin:MapPlugin']).
                   If None, prompts interactively.

    Returns:
        Path to the written config file.

    Raises:
        PtyKitConfigError: If the config file cannot be written.
    """
    print(f"\nptykit init — configuring: {program}")
    print("=" * 50)

    if intercept is None:
        intercept = _prompt_intercept()

    if plugins is None:
        plugins = _prompt_plugins()

    config = {
        "program": program,
        "intercept": intercept,
        "plugins": plugins,
    }

    dest = config_path(program)

    if dest.exists():
        _confirm_overwrite(dest, config)

    _write_config(dest, config)
    return dest


# ---------------------------------------------------------------------------
# Interactive prompts
# ---------------------------------------------------------------------------

def _prompt_intercept() -> list[str]:
    """
    Prompt for the list of commands to intercept.

    Returns:
        List of lowercase command strings.
    """
    print("\nCommands to intercept (comma-separated).")
    print("These are typed by the player but handled by ptykit,")
    print("not passed to the wrapped program.")
    print("Example: map, hint, help")

    while True:
        raw = input("\nIntercept commands: ").strip()
        if raw:
            return [c.strip().lower() for c in raw.split(",") if c.strip()]
        print("At least one command required.")


def _prompt_plugins() -> list[str]:
    """
    Prompt for the list of plugins to activate.

    Returns:
        List of dotted plugin path strings.
    """
    print("\nPlugins to activate (comma-separated dotted paths).")
    print("Example: ptykit_ccc.map_plugin:MapPlugin")
    print("Leave blank for no plugins.")

    raw = input("\nPlugins: ").strip()
    if not raw:
        return []
    return [p.strip() for p in raw.split(",") if p.strip()]


# ---------------------------------------------------------------------------
# Shared helpers
# ---------------------------------------------------------------------------

def _confirm_overwrite(dest: Path, new_config: dict) -> None:
    """
    Show existing and new config, prompt to confirm overwrite.

    Args:
        dest:       Path to the existing config file.
        new_config: The new config dict to be written.
    """
    print(f"\nConfig already exists: {dest}")
    print("\nExisting config:")
    print(dest.read_text(encoding="utf-8"))
    print("New config:")
    print(yaml.dump(new_config, default_flow_style=False, sort_keys=False))

    answer = input("Overwrite existing config? [y/N]: ").strip().lower()
    if answer != "y":
        print("Aborted. Existing config unchanged.")
        sys.exit(0)


def _write_config(dest: Path, config: dict) -> None:
    """
    Write a config dict to disk as YAML.

    Args:
        dest:   Destination path for the config file.
        config: Config dict to serialise.

    Raises:
        PtyKitConfigError: If the file cannot be written.
    """
    header = (
        f"# ptykit config — generated by ptykit init\n"
        f"# Edit manually or regenerate with: "
        f"ptykit init {config['program']}\n\n"
    )
    try:
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_text(
            header + yaml.dump(
                config, default_flow_style=False, sort_keys=False
            ),
            encoding="utf-8",
        )
        print(f"\nWritten: {dest}")
        print(f"Run with: ptykit --program {config['program']}")
    except OSError as exc:
        raise PtyKitConfigError(
            f"Could not write config {dest}: {exc}"
        ) from exc
